/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectPackage;

import javax.swing.JOptionPane;

/**
 *
 * @author elouan
 */
public class interfaceEvent extends javax.swing.JFrame {

    /**
     * Creates new form interfaceEvent
     */
    public interfaceEvent() {
        DAO<Salle> uneSalle = new SalleDAO();
/*        while(SalleDao.find(uneSalle)) {
            
        }*/
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        frmIntitule = new javax.swing.JTextField();
        frmDuree = new javax.swing.JTextField();
        frmDate = new javax.swing.JTextField();
        frmNbPartMax = new javax.swing.JTextField();
        frmOrganisateur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        frmTheme = new javax.swing.JComboBox<>();
        frmNumSalle = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        frmDescription = new javax.swing.JTextArea();
        btnValider = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        label4 = new java.awt.Label();
        btnRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 84, 116));

        jPanel1.setBackground(new java.awt.Color(0, 84, 116));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(245, 245, 245));
        jLabel1.setText("Ajouter un nouvel évênement");

        frmDuree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmDureeActionPerformed(evt);
            }
        });

        frmDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmDateActionPerformed(evt);
            }
        });

        frmNbPartMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmNbPartMaxActionPerformed(evt);
            }
        });

        frmOrganisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmOrganisateurActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(242, 241, 240));
        jLabel3.setText("Intitulé :");

        jLabel4.setForeground(new java.awt.Color(242, 241, 240));
        jLabel4.setText("Thème :");

        jLabel5.setForeground(new java.awt.Color(242, 241, 240));
        jLabel5.setText("Date début :");

        jLabel6.setForeground(new java.awt.Color(242, 241, 240));
        jLabel6.setText("Durée :");

        jLabel7.setForeground(new java.awt.Color(242, 241, 240));
        jLabel7.setText("Nombre maximum de participants :");

        jLabel9.setForeground(new java.awt.Color(242, 241, 240));
        jLabel9.setText("Numéro salle :");

        jLabel10.setForeground(new java.awt.Color(242, 241, 240));
        jLabel10.setText("Organisateur :");

        frmTheme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coupe de cheveux", "Barmitzvah", "Batmitzvah", "Fête de la kippa", "Fête de la farine", "Chabbat" }));
        frmTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmThemeActionPerformed(evt);
            }
        });

        frmNumSalle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "121", "122", "123", "124" }));
        frmNumSalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frmNumSalleActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(242, 241, 240));
        jLabel2.setText("Description :");

        frmDescription.setColumns(20);
        frmDescription.setRows(5);
        frmDescription.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(frmDescription);

        btnValider.setText("Valider");
        btnValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValiderActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 63, 87));

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setBackground(new java.awt.Color(0, 63, 87));
        label4.setFont(new java.awt.Font("SansSerif", 0, 9)); // NOI18N
        label4.setForeground(new java.awt.Color(254, 254, 254));
        label4.setText("Copyright 2016 | Développé par Alexy, Elouan, Maxime, Shemseddine");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnRetour.setText("<- Retour");
        btnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(289, 289, 289))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(174, 174, 174)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frmIntitule, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frmTheme, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(frmDate, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frmDuree, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frmNumSalle, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(frmOrganisateur, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(frmNbPartMax, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 70, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frmIntitule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frmTheme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frmDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frmDuree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frmNumSalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frmOrganisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frmNbPartMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnValider)
                    .addComponent(btnRetour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frmThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmThemeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frmThemeActionPerformed

    private void frmDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frmDateActionPerformed

    private void frmDureeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmDureeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frmDureeActionPerformed

    private void frmNumSalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmNumSalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frmNumSalleActionPerformed

    private void frmOrganisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmOrganisateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frmOrganisateurActionPerformed

    private void frmNbPartMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frmNbPartMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_frmNbPartMaxActionPerformed

    private void btnValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValiderActionPerformed
        boolean erreur = false;

        String lesErreurs,
                theme,
                intitule,
                date,
                organisateur,
                description;

        int duree,
                numSalle,
                nbPartMax;

        lesErreurs = "";

        if (frmIntitule.getText().length() <= 0) {
            erreur = true;
            lesErreurs += "\nL'intitulé doit être renseigné.";
        }
        if (frmTheme.getSelectedItem().toString().length() <= 0) {
            erreur = true;
            lesErreurs += "\nLe thème doit être renseigné.";
        }
        if (frmDate.getText().length() <= 0) {
            erreur = true;
            lesErreurs += "\nLa date doit être renseigné.";
        }
        if (frmDuree.getText().length() <= 0) {
            erreur = true;
            lesErreurs += "\nLa durée doit être renseigné.";
        }
        if (frmNumSalle.getSelectedItem().toString().length() <= 0) {
            erreur = true;
            lesErreurs += "\nLe numéro doit être renseigné.";
        }
        if (frmOrganisateur.getText().length() <= 0) {
            erreur = true;
            lesErreurs += "\nL'organisateur doit être renseigné.";
        }
        if (frmNbPartMax.getText().length() <= 0) {
            erreur = true;
            lesErreurs += "\nLe nombre maximal de participant doit être renseigné.";
        }
        if (frmDescription.getText().length() <= 0) {
            erreur = true;
            lesErreurs += "\nLa description doit être renseigné.";
        }

        if (erreur == true) {
            JOptionPane d = new JOptionPane();
            d.showMessageDialog(this, lesErreurs,
                    "Problème !", JOptionPane.INFORMATION_MESSAGE);
            lesErreurs = "";
            erreur = false;
        } else {
            intitule = frmIntitule.getText();
            theme = frmTheme.getSelectedItem().toString();
            date = frmDate.getText();
            try {
                duree = Integer.parseInt(frmDuree.getText());
            } catch (NumberFormatException e) {
                JOptionPane d = new JOptionPane();
                d.showMessageDialog(this, "La durée doit être un entier.",
                        "Problème !", JOptionPane.INFORMATION_MESSAGE);
            }
            try {
                numSalle = Integer.parseInt(frmNumSalle.getSelectedItem().toString());
            } catch (NumberFormatException e) {
                JOptionPane d = new JOptionPane();
                d.showMessageDialog(this, "Le numéro de la salle doit être un entier.",
                        "Problème !", JOptionPane.INFORMATION_MESSAGE);
            }
            organisateur = frmOrganisateur.getText();
            try {
                nbPartMax = Integer.parseInt(frmNbPartMax.getText());
            } catch (NumberFormatException e) {
                JOptionPane d = new JOptionPane();
                d.showMessageDialog(this, "Le nombre maximal de participants  doit être un entier.",
                        "Problème !", JOptionPane.INFORMATION_MESSAGE);
            }
            description = frmDescription.getText();

            duree = Integer.parseInt(frmDuree.getText());
            numSalle = Integer.parseInt(frmNumSalle.getSelectedItem().toString());
            nbPartMax = Integer.parseInt(frmNbPartMax.getText());

            Evenement nouvelEvent = new Evenement(theme, intitule, date, organisateur, description, duree, numSalle, nbPartMax);
            DAO<Evenement> eventDao = new EvenementDAO();
            eventDao.create(nouvelEvent);
            
            JOptionPane d = new JOptionPane();
            d.showMessageDialog(this, "L'évênement a bien été ajouté.",
            "Succès !", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnValiderActionPerformed

    private void btnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourActionPerformed
        interfaceHome paneHome = new interfaceHome();
        this.setVisible(false);
        paneHome.setVisible(true);
    }//GEN-LAST:event_btnRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaceEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRetour;
    private javax.swing.JButton btnValider;
    private javax.swing.JTextField frmDate;
    private javax.swing.JTextArea frmDescription;
    private javax.swing.JTextField frmDuree;
    private javax.swing.JTextField frmIntitule;
    private javax.swing.JTextField frmNbPartMax;
    private javax.swing.JComboBox<String> frmNumSalle;
    private javax.swing.JTextField frmOrganisateur;
    private javax.swing.JComboBox<String> frmTheme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
}
